services:
  warehouse-v2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-v2
    restart: unless-stopped
    ports:
      - "8070:80"
    volumes:
      - warehouse_data_v2:/var/warehouse_data
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DATA_PATH=/var/warehouse_data

volumes:
  warehouse_data_v2:
    name: warehouse_storage_v2
