services:
  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-acceptance
    restart: unless-stopped
    ports:
      - "8070:80"
    volumes:
      - warehouse_data:/var/warehouse_data
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DATA_PATH=/var/warehouse_data

volumes:
  warehouse_data:
    name: warehouse_storage
